# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/arty_eth.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_mig_7series_0_0/top_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mig_7series_0_0 || ORIG_REF_NAME==top_mig_7series_0_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_0/top_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_0 || ORIG_REF_NAME==top_microblaze_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_v10_0/top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_v10_0/top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_lmb_bram_0/top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_4/top_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_4 || ORIG_REF_NAME==top_auto_pc_4} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_0/top_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_0 || ORIG_REF_NAME==top_auto_us_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_1/top_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_1 || ORIG_REF_NAME==top_auto_us_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_2/top_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_2 || ORIG_REF_NAME==top_auto_us_2} -quiet] -quiet

# IP: bd/top/ip/top_auto_ds_0/top_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_ds_0 || ORIG_REF_NAME==top_auto_ds_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_ds_1/top_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_ds_1 || ORIG_REF_NAME==top_auto_ds_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_1/top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_ds_2/top_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_ds_2 || ORIG_REF_NAME==top_auto_ds_2} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_2/top_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_2 || ORIG_REF_NAME==top_auto_pc_2} -quiet] -quiet

# IP: bd/top/ip/top_auto_ds_3/top_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_ds_3 || ORIG_REF_NAME==top_auto_ds_3} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_3/top_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_3 || ORIG_REF_NAME==top_auto_pc_3} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_axi_periph_0/top_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_axi_periph_0 || ORIG_REF_NAME==top_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_axi_intc_0/top_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_axi_intc_0 || ORIG_REF_NAME==top_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_xlconcat_0/top_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_xlconcat_0 || ORIG_REF_NAME==top_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/top/ip/top_mdm_1_0/top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_mig_7series_0_83M_0/top_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==top_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_ethernetlite_0_0/top_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_ethernetlite_0_0 || ORIG_REF_NAME==top_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_timer_0_0/top_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_timer_0_0 || ORIG_REF_NAME==top_axi_timer_0_0} -quiet] -quiet

# XDC: /home/eliquinox/code/fpga/microblaze-ethernet/microblaze-ethernet.gen/sources_1/bd/top/top_ooc.xdc
